import type { View } from '../useFleetView';
import { Btn } from './Btn';
import { BrandIcon, CloseIcon, GpsIcon } from '../icons';
import { cardTight } from '../styles';

export function DetailDrawer({ v }: { v: View }) {
  if (!v.hasDetail) return null;
  const d = v.detail;
  return (
    <div onClick={v.closeDetail} style={{ position: 'fixed', inset: 0, background: 'rgba(22,21,15,0.42)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, zIndex: 65 }}>
      <div onClick={(e) => e.stopPropagation()} style={{ width: 1000, maxWidth: '100%', maxHeight: '92vh', overflowY: 'auto', background: '#f4f0e8', borderRadius: 24, padding: 22, display: 'flex', flexDirection: 'column', gap: 12, boxShadow: '0 24px 60px rgba(22,21,15,0.3)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 13 }}>
          <span style={{ width: 46, height: 46, borderRadius: 14, background: '#fffdf8', border: '1px solid #ece4d6', color: '#4a463c', display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 'none' }}><BrandIcon model={d.rawModel} size={27} /></span>
          <div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 22, fontWeight: 700 }}>{d.plate}</div><div style={{ fontSize: 12, color: '#6b665c', marginTop: 2, display: 'flex', alignItems: 'center', gap: 7, flexWrap: 'wrap' }}><span>{d.model}</span><span style={{ width: 3, height: 3, borderRadius: 2, background: '#c9c2b4' }} /><span>{d.gpsTag}</span></div></div>
          <span style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', padding: '6px 11px', borderRadius: 12, background: d.estadoBg, color: d.estadoFg }}>{d.estado}</span>
          <Btn onClick={d.agregarDatos} style={{ border: '1px solid #e0d6c4', background: '#fffdf8', color: '#8d5c10', borderRadius: 12, minHeight: 38, padding: '0 14px', fontSize: 12, fontWeight: 700, cursor: 'pointer' }} hoverStyle={{ background: '#f7f1e5' }}>Editar datos</Btn>
          <Btn onClick={v.closeDetail} ariaLabel="Cerrar" style={{ width: 38, height: 38, borderRadius: 19, border: '1px solid #e6ded0', background: '#fffdf8', cursor: 'pointer', color: '#3d3a34', display: 'flex', alignItems: 'center', justifyContent: 'center' }} hoverStyle={{ background: '#f7f1e5' }}><CloseIcon size={16} /></Btn>
        </div>

        <div style={{ ...cardTight, padding: 16, display: 'flex', alignItems: 'center', gap: 14 }}><span style={{ width: 40, height: 40, borderRadius: 13, background: d.location && !d.location.stale ? '#eef4f0' : '#fdf3e2', color: d.location && !d.location.stale ? '#2e7d5b' : '#a8730f', display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 'none' }}><GpsIcon size={19} /></span><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#6b665c' }}>Ubicación del teléfono</div><div style={{ fontSize: 13, fontWeight: 700, marginTop: 3 }}>{d.location ? (d.location.stale ? 'Ubicación desactualizada' : 'Auto localizado') : 'Nunca se recibió una ubicación'}</div>{d.location && <div style={{ fontSize: 11, color: '#6b665c', marginTop: 2 }}>{d.location.age} · precisión ±{Math.round(d.location.accuracy ?? 0)} m</div>}</div>{d.location && <a href={d.location.mapsUrl} target="_blank" rel="noreferrer" style={{ color: '#8d5c10', fontSize: 12, fontWeight: 700 }}>Abrir mapa</a>}</div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10 }}><Metric label="Ingresos reales" value={d.ing} color="#2e7d5b" /><Metric label="Gastos" value={d.egr} color="#c0553f" /><Metric label="Resultado" value={d.net} color="#fffdf8" dark /></div>

        <div className="detalle-cols" style={{ minHeight: 0 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <section style={{ ...cardTight, padding: 16 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#6b665c' }}>Chofer</div><div style={{ fontSize: 16, fontWeight: 700, marginTop: 5 }}>{d.driver}</div><div style={{ fontSize: 12, color: '#6b665c', marginTop: 3 }}>{d.hasDriver ? `Cuota diaria ${d.cuotaFmt} · ${d.cobradas}` : 'Sin chofer asignado'}</div><div style={{ fontSize: 12, color: '#6b665c', paddingTop: 12, marginTop: 12, borderTop: '1px solid #f0ebe0' }}>{d.pendientes}</div></section>
            <section style={{ ...cardTight, padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><span style={{ flex: 1, fontSize: 15, fontWeight: 700 }}>Mantenimiento</span><Btn onClick={d.markService} style={{ border: 'none', background: '#16150f', color: '#fffdf8', borderRadius: 12, minHeight: 36, padding: '0 14px', fontSize: 12, fontWeight: 700, cursor: 'pointer' }} hoverStyle={{ background: '#2a2820' }}>Registrar service</Btn></div><div style={{ padding: '10px 12px', borderRadius: 12, background: '#f7f3eb' }}><div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', color: '#6b665c' }}>Kilometraje actual</div><div style={{ fontSize: 15, fontWeight: 700, marginTop: 3 }}>{d.kilometraje}</div><div style={{ fontSize: 11, color: '#6b665c', marginTop: 2 }}>{d.kilometrajeSub}</div></div><div style={{ height: 8, borderRadius: 4, background: '#f0ebe0', overflow: 'hidden' }}><span style={{ display: 'block', height: '100%', borderRadius: 4, background: d.svcBar, width: d.svcPct }} /></div><div><div style={{ fontSize: 13, fontWeight: 600, color: d.svcFg }}>{d.svcLbl}</div><div style={{ fontSize: 12, color: '#6b665c', marginTop: 3 }}>{d.svcSub}</div></div><div style={{ borderTop: '1px solid #f0ebe0', paddingTop: 12, fontSize: 12, color: '#6b665c' }}>Los datos de kilometraje, service y seguro se editan juntos desde <strong>Editar datos</strong>.</div></section>
            <section style={{ ...cardTight, padding: 16 }}><div style={{ fontSize: 15, fontWeight: 700 }}>Estado del vehículo</div><div style={{ fontSize: 12, color: '#6b665c', marginTop: 7 }}>Estado actual: <strong>{d.estado}</strong>. Para cambiarlo, usá Editar datos.</div></section>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0 }}>
            <section style={{ ...cardTight, padding: 16 }}><div style={{ fontSize: 15, fontWeight: 700, marginBottom: 12 }}>Mes a mes</div><div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>{d.months.map((m) => <div key={m.label} style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ width: 34, fontSize: 12, fontWeight: 700, color: '#6b665c', textTransform: 'uppercase' }}>{m.label}</span><span style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 3 }}><span style={{ height: 8, borderRadius: 4, background: '#f0ebe0' }}><span style={{ display: 'block', height: '100%', borderRadius: 4, background: '#2e7d5b', width: m.ingPct }} /></span><span style={{ height: 8, borderRadius: 4, background: '#f0ebe0' }}><span style={{ display: 'block', height: '100%', borderRadius: 4, background: '#c0553f', width: m.egrPct }} /></span></span><span style={{ width: 82, textAlign: 'right', fontSize: 13, fontWeight: 700, color: m.netFg }}>{m.net}</span></div>)}</div></section>
            <section style={{ ...cardTight, padding: 16, display: 'flex', flexDirection: 'column', minHeight: 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 7 }}><span style={{ flex: 1, fontSize: 15, fontWeight: 700 }}>Últimos movimientos reales</span><Btn onClick={d.verHistorial} style={{ border: 'none', background: 'none', color: '#8d5c10', fontSize: 12, fontWeight: 700, cursor: 'pointer' }} hoverStyle={{ color: '#b5791a' }}>Ver historial</Btn></div><div className="scroll-sin-barra" style={{ overflowY: 'auto' }}>{d.movs.length ? d.movs.map((m, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 0', borderBottom: '1px solid #f4efe4' }}><span style={{ width: 30, height: 30, borderRadius: 10, background: m.iconBg, color: m.iconFg, display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 'none', fontWeight: 800 }}>{m.sign}</span><span style={{ flex: 1, minWidth: 0 }}><span style={{ display: 'block', fontSize: 12, fontWeight: 600 }}>{m.desc}</span><span style={{ display: 'block', fontSize: 11, color: '#6b665c', marginTop: 2 }}>{m.dateLbl} · {m.sub}</span></span><span style={{ fontSize: 13, fontWeight: 700, color: m.amtFg }}>{m.amt}</span></div>) : <div style={{ padding: '25px 0', color: '#6b665c', fontSize: 12, textAlign: 'center' }}>Todavía no hay movimientos reales para este vehículo.</div>}</div></section>
          </div>
        </div>
      </div>
    </div>
  );
}

function Metric({ label, value, color, dark = false }: { label: string; value: string; color: string; dark?: boolean }) { return <div style={{ background: dark ? '#16150f' : '#fffdf8', border: dark ? 'none' : '1px solid #ece4d6', borderRadius: 16, padding: '13px 14px' }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: dark ? '#bdb6a4' : '#6b665c' }}>{label}</div><div style={{ fontSize: 18, fontWeight: 700, marginTop: 5, color }}>{value}</div></div>; }
